name: Autorelease

on:
  push:
    branches:
     - master

jobs:
  autotag:
    runs-on: ubuntu-latest
    
    steps:
    - name: Automatically tag new versions.
      uses: author/action-autotag@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
