on:
  push:
    branches:
     - master

jobs:
  autotag:
    runs-on: ubuntu-latest
    steps:
    - name: "Autotag"
      uses: author/action-autotag@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
